all:
  children:
    critchley:
      hosts:
        clean3:
          ansible_user: admin
          ansible_ssh_private_key_file: /home/john/.ssh/clean3.pem
      vars:
          ansible_python_interpreter: /usr/bin/python3

