all:
  children:
    critchley:
      hosts:
        control:
          instance_type: t3.medium
        wednesday:
          instance_type: t3.medium
        thursday:
          instance_type: t3.small
      vars:
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: admin
          ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/{{ inventory_hostname }}.pem"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
